CREATE TABLE news
(
    id SERIAL PRIMARY KEY,
    author VARCHAR(50)  NOT NULL,
    title  VARCHAR(250) NOT NULL UNIQUE,
    body   TEXT NOT NULL ,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
);


