// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"
	models "news/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// RedisRepository is an autogenerated mock type for the RedisRepository type
type RedisRepository struct {
	mock.Mock
}

// GetNewsByIDCtx provides a mock function with given fields: ctx, key
func (_m *RedisRepository) GetNewsByIDCtx(ctx context.Context, key string) (*models.News, error) {
	ret := _m.Called(ctx, key)

	var r0 *models.News
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.News); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.News)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetNewsCtx provides a mock function with given fields: ctx, key, seconds, news
func (_m *RedisRepository) SetNewsCtx(ctx context.Context, key string, seconds int, news *models.News) error {
	ret := _m.Called(ctx, key, seconds, news)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, *models.News) error); ok {
		r0 = rf(ctx, key, seconds, news)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
