app:
  env: 'dev'
  port: 3000
postgres:
    host: localhost
    port: 5432
    schema: public
    dbName: news
    user: novienghi
    password: 12345678
    sslmode: "disable"
    loc: "Asia/Jakarta"
redis:
  host: localhost:6379
  password: ''